package com.example.syngrychallenge.model

data class WordListModel(
    val wordAre: List<WordModel> = listOf(
        WordModel("Ayam"),
        WordModel("Asik"),
        WordModel("Air"),
        WordModel("Asam"),
        WordModel("Basi"),
        WordModel("Basah"),
        WordModel("Berantam"),
        WordModel("Borak"),
        WordModel("Cloudflare"),
        WordModel("Composable"),
        WordModel("CSS"),
        WordModel("cok"),
        WordModel("Dongkol"),
        WordModel("Dobrak"),
        WordModel("Dosa"),
        WordModel("Doremi"),
        WordModel("Enak"),
        WordModel("Elektronik"),
        WordModel("Erat"),
        WordModel("Encok"),
        WordModel("Fair"),
        WordModel("Food"),
        WordModel("Far"),
        WordModel("fart"),
        WordModel("Goreng"),
        WordModel("Goyang"),
        WordModel("Golek"),
        WordModel("Golok"),
        WordModel("Hari"),
        WordModel("Haram"),
        WordModel("Haiya"),
        WordModel("Horang"),
        WordModel("Ilalang"),
        WordModel("Ireng"),
        WordModel("Isap"),
        WordModel("Itam"),
        WordModel("Jangkung"),
        WordModel("Jangkrik"),
        WordModel("Jarot"),
        WordModel("Jarang"),
    )
)
